/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PScKSjnOyTw
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import { Button } from "@/components/ui/button";
import Link from "next/link";
import img from "../images/z2.jpg";
import Image from "next/image";
import { useEffect, useState } from "react";
import axios from "axios";
import { Card, CardBody, CardFooter } from "@nextui-org/react";

interface Product {
  _id: string;
  name: string;
  des: string;
  type: Array<string>;
  size: Array<string>;
  oriPrice: number;
  disPrice: number;
  images: string;
}

export function CardProduct() {
  const [data, setData] = useState([]);

  useEffect(() => {
    const getData = async () => {
      const res = await axios.get("/api/getData");
      console.log(setData(res.data));
    };

    getData();
  }, []);
  return (
    <section className="w-full py-12">
      <div className="container grid gap-8 md:gap-12 px-4 md:px-6">
        <div className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
          <div className="grid gap-1">
            <h1 className="text-2xl font-bold tracking-tight">
              Fall Fashion Collection
            </h1>
            <p className="text-gray-500 dark:text-gray-400">
              Discover the latest trends and styles for the season.
            </p>
          </div>
          {/* <Button className="md:ml-auto shrink-0" size="lg" variant="outline">
            View all
          </Button> */}
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
          {data.map((item: Product, index) => (
            
            <div className="grid gap-4 ">
              <div className="grid gap-2.5 relative group">
                <Card
                  className="min-h-[450px] max-h-[5000px] bg-gray-200"
                  shadow="sm"
                  key={index}
                  isPressable
                  onPress={() => console.log("item pressed")}
                >
                  <Link className="absolute inset-0 z-10" href={`/product/${item._id}`}></Link>
                    
                  <CardBody className="truncate p-0">
                    <Image
                      alt="Leather Jacket"
                      className="rounded-lg object-cover w-full aspect-[3/4] group-hover:opacity-50 transition-opacity gap-y-3"
                      height={400}
                      src={item.images}
                      width={300}
                    />
                  </CardBody>
                  <CardFooter className="text-md justify-between">
                  <div className="grid gap-2">
                    <h3 className="font-semibold overflow-hidden h-7 text-md text-start gap-y-3">{item.name}</h3>
                    <p className="text-sm overflow-hidden h-11 leading-normal text-start">
                      {item.des}
                    </p>
                    <div className="flex items-center justify-between">
                      <span className="font-semibold">{item.disPrice} $</span>
                        {/* <Link className="absolute inset-0 z-10" href="#">
                          <span className="sr-only">View</span>
                        </Link>
                      <Button size="sm" variant="outline">
                        Add to Cart
                      </Button> */}
                    </div>
                  </div>
                  </CardFooter>
                </Card>
              </div>
            </div>
          ))}

        </div>
      </div>
    </section>
  );
}
