/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PGlekixZpLg
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import Logo from "./Logo";
import { Label } from "./ui/label";
import Logo1 from "./Logo1";

export function Footer() {
  return (
    <footer className="bg-gray-100 py-12">
      <div className="container mx-auto px-4 md:px-6 mt-8 max-w-7xl grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="flex flex-col items-start gap-4">
          <Link
            className="flex items-center gap-2 text-lg font-semibold md:text-base"
            href="/dashboard"
          >
            <Logo1 />
          </Link>
          <p className="text-gray-500">
            We want to acquire a good portion market in mfg. of garments and as
            we will grow forward, we want to do a joint venture in Ceramic
            Industry.
          </p>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-6">
          <div className="grid gap-2">
            <h3 className="font-semibold">Quick Links</h3>
            <Link
              className="text-gray-500 hover:text-gray-900"
              href="/dashboard"
            >
              Home
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900"
              href="/products"
            >
              Shop
            </Link>
            <Link className="text-gray-500 hover:text-gray-900" href="/aboutus">
              About Us
            </Link>
            <Link className="text-gray-500 hover:text-gray-900" href="contact">
              Contact Us
            </Link>
          </div>
          <div className="grid gap-2">
            <h3 className="font-semibold">Our Categories</h3>
            <Link className="text-gray-500 hover:text-gray-900" href="/category/Kurti">
              Kurti
            </Link>
            <Link className="text-gray-500 hover:text-gray-900" href={`/category/Pant Pair`}>
              Pair Pant
            </Link>
            <Link className="text-gray-500 hover:text-gray-900 " href="/category/Gown">
              Gown
            </Link>
            <Link className="text-gray-500 hover:text-gray-900 " href={`/category/Plaza Pair`}>
              Plaza Pair
            </Link>
            <Link className="text-gray-500 hover:text-gray-900" href={`/category/Nayra Pair`}>
              Nayra Pair
            </Link>
          </div>
          <div className="grid gap-2">
            <h3 className="font-semibold">Our Policies</h3>
            <Link className="text-gray-500 hover:text-gray-900" href="/terms">
              Terms of Service
            </Link>
            <Link className="text-gray-500 hover:text-gray-900" href="/privacy">
              Privacy Policy
            </Link>
            <Link className="text-gray-500 hover:text-gray-900" href="/returns">
              Return Policy
            </Link>
            <Link className="text-gray-500 hover:text-gray-900" href="/delivery">
              Delivery Policy
            </Link>
          </div>
        </div>
        <div className="flex flex-col items-start gap-4">
          <h3 className="font-semibold">Contact Us</h3>
          <div className="flex flex-col gap-4">
            <Link className="text-gray-500  hover:text-gray-900" href="#">
              <Label className="capitalize">
                SHOP-31 GROUND FLOOR, SHRI VINAYAK ARCADE, Krishna Park Twp,
                Mota Varachha, Surat, Shiv Nagar, Gujarat 394101
              </Label>
            </Link>
            <div className="flex items-center gap-2">
              <MailIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
              <a className="text-gray-500 hover:text-gray-900" href="#">
                aavkarfashion71@gmail.com
              </a>
            </div>
            <div className="flex items-center gap-2">
              <PhoneIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
              <a className="text-gray-500 hover:text-gray-900" href="#">
                +91 9998264004
              </a>
            </div>
            <div className="flex flex-row gap-3">
              <Link className="text-gray-500 hover:text-gray-900" href="https://www.instagram.com/eroe_designer?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==">
                <InstagramIcon className="h-6 w-6" />
              </Link>
              <Link className="text-gray-500 hover:text-gray-900" href="https://www.facebook.com/piyush.donga.908">
                <FacebookIcon className="h-6 w-6"/>
              </Link>
              <Link className="text-gray-500 hover:text-gray-900" href="#">
                <TwitterIcon className="h-6 w-6" />
              </Link>
              <Link className="text-gray-500 hover:text-gray-900" href="#">
                <MailIcon className="h-6 w-6" />
              </Link>
            </div>
          </div>
        </div>
      </div>
      <div className="container mx-auto px-4 md:px-6 mt-8 mb-0 pb-0 border-t pt-4 flex items-center justify-between">
        <p className="text-sm text-gray-500">
          © 2025 Aavkar Fashion All rights reserved.
        </p>
        <nav className="flex items-center gap-4">
          <Link target="_" className="text-sm text-gray-500 hover:text-gray-900" href="https://api.whatsapp.com/send/?phone=917818070999&text&type=phone_number&app_absent=0">
            Developed By Abhay Donga
          </Link>
        </nav>
      </div>
    </footer>
  );
}

function MailIcon({ ...props }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

function PhoneIcon({ ...props }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  );
}

function MapPinIcon({ ...props }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  );
}

function FacebookIcon({ ...props }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  );
}

function InstagramIcon({ ...props }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  );
}

function LinkedinIcon({ ...props }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function MountainIcon({ ...props }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}

function TwitterIcon({ ...props }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}
