/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/i1SPYgl8dyX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import { Label } from "@/components/ui/label"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Badge } from "@/components/ui/badge"
import { Nav } from "./Nav";
import Image from "next/image";
import img from '@/images/z2.jpg'
import { useEffect, useState } from "react";
import axios from "axios";
import { Button } from "@nextui-org/button";
import { useCounter } from '@mantine/hooks';
import { useSession } from "@clerk/nextjs";
        

type Props = {
  id: string,
};

interface Product {
  name: string;
  des: string;
  type: Array<string>;
  size: Array<string>;
  oriPrice: number;
  disPrice: number;
  images: string;
}

export function Product(props: Props) {
  const { id } = props;
  const [count, handlers] = useCounter(1,{ min: 1, max: 30 });
  const session = useSession();
  const userId = session.session?.user.id
  
  const [product, setProduct] = useState<Product>();
  useEffect(() => {

    const getData = async () => {
      const res = await axios.get(`/api/getDataById?id=${id}`);
      setProduct(res.data)
    };

    getData();
  }, [id]);

  const handleCart = async () => {
    const Cart = await fetch("/api/addToCart",{
      method:'POST',
      headers:{
        "Content-Type":"application/json"
      },
      body:JSON.stringify({userId,id,count}),
    });
    console.log(Cart.json());
    
  }

  return (
    <div>
      <Nav />
    <div className="grid md:grid-cols-2 gap-6 lg:gap-12 items-start max-w-6xl mx-auto py-6">
      <div className="h-max-[10px]">
        <Image
            alt="Sneaker Image"
            className="rounded-3xl w-auto h-auto"
            src={product?.images!}
            width={300}
            height={400}
          />
      </div>
      <div className="grid gap-4 md:gap-8">
        <div>
          <h1 className="text-3xl font-bold pb-5">{product?.name}</h1>
          <p className="text-gray-500 dark:text-gray-400 text-md">
            {product?.des}
          </p>
        </div>
        <div className="grid gap-2 ">
          <div className="flex items-center gap-2 pb-3">
            <div className="text-4xl font-bold">$ {product?.disPrice}</div>
            <div className="text-2xl font-bold text-gray-500 line-through">$ {product?.oriPrice}</div>
            <div className="bg-green-500 text-white px-2 py-1 rounded-md text-sm font-medium">20% off</div>
          </div>
          <div className="grid gap-2 pb-3">
            <Label className="text-base" htmlFor="size">
              Size
            </Label>
            <Select defaultValue="m">
              <SelectTrigger>
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="s">S</SelectItem>
                <SelectItem value="m">M</SelectItem>
                <SelectItem value="l">L</SelectItem>
                <SelectItem value="xl">XL</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="grid gap-2 pb-3">
            <Label className="text-base">Size Options</Label>
            <div className="flex items-center gap-2">
              <Button className="rounded-full" size="sm">
                S
              </Button>
              <Button className="rounded-full" size="sm">
                M
              </Button>
              <Button className="rounded-full" size="sm">
                L
              </Button>
              <Button className="rounded-full" size="sm">
                XL
              </Button>
            </div>
          </div>
          <div className="grid gap-2 pb-3">
            <Label className="text-base">Product Type</Label>
            <div className="flex items-center gap-2">
              <Badge className="bg-blue-500 text-white">Running</Badge>
              <Badge className="bg-gray-200 text-gray-800 dark:bg-gray-800 dark:text-gray-200">Casual</Badge>
              <Badge className="bg-green-500 text-white">Comfort</Badge>
              <Badge className="bg-purple-500 text-white">Lifestyle</Badge>
            </div>
          </div>
          <div className="grid gap-2 pb-3">
            <Label className="text-base">Product Details</Label>
            <div className="text-gray-500 dark:text-gray-400 text-sm">
              <ul className="list-disc pl-4 space-y-1">
                <li>Breathable mesh upper for enhanced airflow</li>
                <li>Cushioned midsole for all-day comfort</li>
                <li>Durable rubber outsole for traction and stability</li>
                <li>Lightweight and flexible design</li>
                <li>Available in a variety of colors</li>
              </ul>
            </div>
          </div>
          <div className="grid gap-2 pb-3">
            <Label className="text-base">Quantity</Label>
            <div className="flex items-center gap-2">
              <Button onClick={handlers.increment} className="rounded-full" size="sm">
                +
              </Button>
              <div className="text-3xl items-center pt-4 font-bold mb-5">{Number(count)}</div>
              <Button onClick={handlers.decrement} className="rounded-full" size="sm">
                -
              </Button>
            </div>
          </div>

          <Button onClick={handleCart} className="w-full" size="lg">
            Add to Cart
          </Button>
        </div>
      </div>
    </div>
    </div>
  )
}
